### ISSUE TITLE
Consider merging stops which are too close (probably are the same stop)

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/o2g#125]
@carocad has this been an issue in Kamal?

**Comment by carocad** [comment]
> an issue in Kamal?

What do you mean? 

So far I didnt even notice it but, to be fair, the routing information is limited since in most cases in only includes one direction which one explain why I never realized that there is a problem.

I think the case that you are referring to is handled in the GTFS spec through `location_type` and `parent_station`; see [stops.txt](https://developers.google.com/transit/gtfs/reference/#stopstxt).

Is this what you are referring to?

**Comment by mehdisadeghi** [comment]
I think this is handled in #126 so I'll close this. We can reopen if there is any specific issue.
