### ISSUE TITLE
consider linking "same stations" but "different stop"

### ISSUE THREAD

**Issue by carocad** [hiposfer/o2g#126]
GTFS feeds have the concept of `parent_station` (see [ref](https://developers.google.com/transit/gtfs/reference/#stopstxt)), whereas in OSM they call it `stop_area`.

Those are basically a way to say that the complete entity is "known" as a single "body" even though it consist of different pieces. I think this is related to #125 however, the proposal here is not to merge them but to link them such that the "belongs to" relation becomes evident

EDIT: this would also imply filling out the `location_type` field as we would have to differentiate between stops and stations

examples:
- https://www.openstreetmap.org/relation/233704#map=15/50.1031/8.6538&layers=T
- https://www.openstreetmap.org/relation/388110#map=18/50.11158/8.65499&layers=T

**Comment by mehdisadeghi** [comment]
It's a while I'm trying to figure out how to do this. There are a few problems. OSM's `stop_area` isn't quite like GTFS' `station`, i.e. it has no coordinates. Therefore coordinate must be inferred from any of its members. In Frankfurt's example above, there are multiple `stations` inside the `stop_area`, my idea was to pick one of them randomly, or just the first one, and use its coordinate.
Next problem is with OSM data. If you compare [Freiburg's Hbf](https://www.openstreetmap.org/relation/1263623) to Frankfurt, you'll realize they are mapped very differently. There are no `stop_area`, instead `stations` and `ways`. Our current overpass query wouldn't even pick it up (since the type is neither `route` nor `stop_area`). I'm not sure whether I have to process stations such as Freiburg since the stops are being already picked up as part their relations. Does the extra complexity worth it?
What do you think @carocad ?

**Comment by mehdisadeghi** [comment]
Moreover I think I'll ignore `platforms` altogether. I'd consider member relations with `stop` role and `stop_position` as stops. If stops is inside a `stop_area` then it might have `parent_station` otherwise not. Platforms inside or outside of a station/stop_area do not have an equivalent GTFS `location_type` and can't be mapped directly.

What do you think?

**Comment by carocad** [comment]
@mehdisadeghi I am not entirely sure if I understand all of the points that you mentioned. I will try to answer based on what I understood 😅 
> If you compare Freiburg's Hbf to Frankfurt, you'll realize they are mapped very differently.

This is actually not correct. I think [this](https://www.openstreetmap.org/relation/6311483) is the entry of the freiburg hbf. It seems that OSM is very specific in differentiating the public transport information from the buildings themselves, which is quite confusing but seems right for mapping purposes.

> I'm not sure whether I have to process stations such as Freiburg since the stops are being already picked up as part their relations. Does the extra complexity worth it?

Sorry, maybe I didnt express myself properly. o2g already does a perfect job of picking those :). The problem is that for big stations, the stops are very far away from each other, which "tricks" kamal into creating walk sections between the stops when it should actually be a `transfer` inside the station. My idea was to "tag" stops as being part of the same station and then use the [transfers](https://developers.google.com/transit/gtfs/reference/#transferstxt) feed from gtfs too create links between the stops that kamal could use.

> Moreover I think I'll ignore platforms altogether. I'd consider member relations with stop role and nodes with public_transport=stop_position tag as stops

not sure I understand everything here; probably since I dont remember how is the current logic for stops. 

> If a stop is inside a stop_area then it might have a parent_station otherwise not. 

I guess this is right 😅 

> Platforms inside or outside of a station/stop_area do not have an equivalent GTFS location_type and can't be mapped directly.

I am not sure I understand this entirely but so far I was only thinking about (gtfs) stations and stops. Basically, whenever you find a gtfs stop, you would clasify it as either stop or station. If it is a station there is no need to do anything special, but if it is a stop then mark it as belonging to the respective station.

I am not sure if this answers the questions that you mentioned above. Let me know if you think this is not right or if I missed something :)
